test_url = "https://qasvus.wordpress.com"
img1 = "//img[@class='wp-image-55']"
img2 = "//img[@class='wp-image-34']"
img3 = "//img[@class='wp-image-56']"
img4 = "//img[@class='wp-image-30']"
vis = "//button[@class='pushbutton-wide']"
name = "//input[@id='g2-name']"
email = "//input[@id='g2-email']"
message = "//textarea[@id='contact-form-comment-g2-message']"
submit = "contact-form-comment-g2-message"
go_back = "//a[contains(text(),'go back')]"
